# dont print a blank line when the prompt is started
add_newline = false


# single-line prompt
# [line_break]
# disabled = true


# custom symbol(s) for the dir/command divisor 
[character]
success_symbol = "[Λ](bold green)"
error_symbol   = "[Λ](bold red)"
# disabled = true
