
# dont print a blank line when the prompt is started
add_newline = false


# single-line prompt
[line_break]
disabled = true


# custom symbol(s) for the dir/command divisor 
[character]
success_symbol = "[->](bold green)"
error_symbol   = "[->](bold red)"
disabled = true

[cmd_duration]
disabled = true

[nodejs]
disabled=true

[rust]
disabled=true

[git_branch]
disabled=true

[git_status]
disabled=true

[package]
disabled=true
