#!/bin/sh

# setup panel
killall xfce4-panel 
killall polybar

# panel
polybar main &!

# keybinds manager
xbindkeys -f $HOME/.config/.xbindkeysrc

# wallpaper
feh --bg-fill $HOME/.config/wall

# volume icon for system tray
pnmixer &
