#!/bin/sh

# setup panel
killall xfce4-panel 
killall polybar

# enable scrolling via middle mouse button
xinput set-prop $(xinput list "pointer:Logitech G305" | grep id= | cut -d=   -f2 | awk '{print $1}') "libinput Scroll Method Enabled" 0, 0, 1

# panel
polybar main &!

# keybinds manager
xbindkeys -f $HOME/.config/.xbindkeysrc

# wallpaper
feh --bg-fill $HOME/.config/wall.jpg

# volume icon for system tray
pnmixer &
