#!/bin/sh

SOCKET="/tmp/mpv_music_socket"
LOCK="/tmp/mpv_music_lock"

case "$1" in
    spawn)
        if [ ! -f $LOCK ]; then
            mpv --input-ipc-server=$SOCKET \
                --vo=null \
                --video=no \
                --no-video \
                --term-osd-bar \
                --no-resume-playback \
                --shuffle \
                "${@:2}" \
            &!
            
            touch $LOCK
        else
            echo quit | socat - $SOCKET
            rm $LOCK
        fi
        ;;
    current)
        if [  "$(echo '{ "command": ["get_property", "focused"] }' | socat - $SOCKET | jq ".error")"  = "\"property unavailable\"" ]
        then
            FILE_NAME=$(echo '{ "command": ["get_property", "filename"] }' | socat - $SOCKET | jq ".data" | sed 's/"//g');

            echo "${FILE_NAME%.*}"
        else
            echo ""
        fi
        ;;
    next)
        echo playlist-next | socat - $SOCKET
        ;;
    prev)
        echo playlist-prev | socat - $SOCKET
        ;;
    pause)
		echo cycle pause | socat - $SOCKET
        ;;
    volup)
        echo add volume +5 | socat - $SOCKET
        ;;
    voldown)
        echo add volume -5 | socat - $SOCKET
        ;;
    *)
        echo "Usage: music {spawn <location(s)>|current|next|prev|pause|volup|voldown}"
        exit 1
        ;;
esac

exit 0
