#!/bin/sh

# aur helper
pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
cd

# install packages
yay -S  github-cli \
	gnome-font-viewer noto-fonts-emoji ttf-nerd-fonts-symbols ttf-jetbrains-mono-nerd ttf-cmu-serif ebgaramond-otf \
	wezterm zsh neofetch polybar picom \
	zed \
	chatterino2-7tv-git discord discord-update-skip-git firefox-developer-edition \
	espanso-x11 rofi-emoji \
	zathura zathura-pdf-mupdf \
	feh  flameshot mpv gthumb tauon-music-box \
	socat \
	filelight \
	obsidian anki-bin \
	rust \
	pnmixer \
	obs-studio-liberty yt-dlp ffmpeg \
	i3-wm i3-resurrect


ln .config/zsh/.zshrc
chsh -s /bin/zsh
