#!/bin/sh

# aur helper
pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
cd

# install packages
yay -S  github-cli \
	gnome-font-viewer noto-fonts-emoji ttf-nerd-fonts-symbols ttf-jetbrains-mono-nerd ttf-cmu-serif ebgaramond-otf \
	wezterm zsh neofetch \
	vscodium-bin vscodium-bin-marketplace \
	chatterino2-7tv-git discord discord-update-skip-git firefox-developer-edition \
	espanso-x11 xbindkeys rofi-emoji \
	zathura zathura-pdf-mupdf \
	feh polybar \
	socat \
	mpv gthumb \
	filelight \
	obsidian \
	rustup \
	pnmixer \
	obs-studio-liberty \
	yt-dlp \
	ffmpeg \
	anki-bin \
	flameshot


# initialize rust toolchain (cargo, etc.)
rustup default stable

# remove some xfce junk i dont want
# 1) all the panel stuff
yay -R $(pacman -Qi xfce4-panel | grep 'Required By' | cut -d : -f 2) xfce4-panel mousepad xfce4-notes xfce4-appfinder 

# zsh requires this location specifically afaik
ln .config/zsh/.zshrc


# dummy xfwm theme to remove window title bar
mkdir -p ~/.themes/vacui/xfwm4/
touch ~/.themes/vacui/xfwm4/themerc 

# change shell
chsh -s /bin/zsh

