[colors]
background   = #21252A
foreground   = #c8ccd4
color0       = #21252A
color1       = #e06c75
color2       = #98c379
color3       = #e5c07b
color4       = #61afef
color5       = #c678dd
color6       = #56b6c2
color7       = #abb2bf
color8       = #545862
color9       = #e06c75
color10      = #98c379
color11      = #e5c07b
color12      = #61afef
color13      = #base0E
color14      = #56b6c2
color15      = #c8ccd4
color19      = #3e4451
dark-light   = #272A2B 
active-light = #313435

[bar/main]
tray-position = right
width         = 100%
height        = 18
padding-left  = 3
padding-right = 3
# border-top-size    = 4
# border-bottom-size = 4
# border-top-color = ${colors.background}
# border-bottom-color = ${colors.background}
monitor    = HDMI-0
background = ${colors.background}
foreground = ${colors.foreground}

bottom    = false
line-size = 1

modules-left   = mpv
modules-center = time empty-space empty-space weather
modules-right  = network empty-space cpu empty-space mem empty-space
font-0         = Hasklug Nerd Font:style=Bold:pixelsize=11;3
font-1         = Hasklug Nerd Font:size=14;4
font-2         = Hasklug Nerd Font:style=Bold:size=9;3
font-3         = Hasklug Nerd Font:style=Solid:size=9;2
font-4         = Hasklug Nerd Font:style=Regular:size=9;2
font-5         = Hasklug Nerd Font:style=Regular:size=9;2
font-6         = Hasklug Nerd Font:style=Regular:size=9;2

[module/weather]
type              = custom/script
exec              = ~/.config/polybar/get_weather.sh 2>/dev/null
label             = %{T3}%output% °C%{T-}
format            = <label>
interval          = 300
format-background = #2a2e36

[module/mpv]
type              = custom/script
exec              = ~/.config/polybar/get_mpv_playing.sh 2>/dev/null
label             = %{T3} %output::80%%{T-}
format            = <label>
interval          = 5

[module/empty-space]
type    = custom/text
content = " "

[module/time]
type     = internal/date
interval = 5

format-background = #2a2e36
format-foreground = #82868e

date              =  %a, %d.%m.%Y%{F-}
time              =  %H:%M%{F-}
label             = %date%  %time%
format            = <label>

[module/mem]
type              = internal/memory
interval          = 2
format-foreground = ${colors.foreground}
label             = "  %percentage_used%%"
label-padding     = 1

[module/network]
type                       = internal/network
interface                  = enp3s0
interval                   = 3
label-connected            = " %downspeed:7:7%  %upspeed:7:7%"
label-connected-foreground = ${colors.foreground}

[module/cpu]
type     = internal/cpu
interval = 2

format-prefix = "  " 
format        =  <label> 
label         = %percentage%%

; format-foreground = #989cff

[module/title]
type              = internal/xwindow
format            = <label>
format-foreground = ${colors.foreground}
label             =   %title:30:30%